// 统一的注入令牌定义
export const INJECTION_TOKENS = {
    // 存储库令牌
    USER_REPOSITORY: 'USER_REPOSITORY',
    MESSAGE_REPOSITORY: 'MESSAGE_REPOSITORY',
    // 服务令牌
    AUTH_SERVICE: 'AUTH_SERVICE',
    // 其他令牌...
};

// 为向后兼容保留，但标记为 @deprecated
/** @deprecated 请使用 INJECTION_TOKENS.USER_REPOSITORY */
export const USER_REPOSITORY_TOKEN = INJECTION_TOKENS.USER_REPOSITORY;
/** @deprecated 请使用 INJECTION_TOKENS.MESSAGE_REPOSITORY */
export const MESSAGE_REPOSITORY_TOKEN = INJECTION_TOKENS.MESSAGE_REPOSITORY; 